monitor.alsa.rules = [
  {
    matches = [
      {
        # 匹配所有输出设备
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        dither.method = "wannamaker3", # add dither of desired shape
        dither.noise = 19, # add additional bits of noise
      }
    }
  }
]
