theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = false
cursorline = true
bufferline = "always"
insert-final-newline = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
#max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it
[keys.select."space"]
y = ":clipboard-yank"

[keys.normal]
"C-left" = ":buffer-previous"
"C-right" = ":buffer-next"
C-j = "page_down"
C-k = "page_up"
C-s = ":w"
V = ["select_mode", "extend_to_line_bounds"]